// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc1982.Robot2017;

import org.usfirst.frc1982.Robot2017.commands._AgitateServoBackward;
import org.usfirst.frc1982.Robot2017.commands._AgitateServoForward;
import org.usfirst.frc1982.Robot2017.commands._AutomateServo;
import org.usfirst.frc1982.Robot2017.commands._CameraCenter;
import org.usfirst.frc1982.Robot2017.commands._DriveEnableRaw;
import org.usfirst.frc1982.Robot2017.commands._Intake;
import org.usfirst.frc1982.Robot2017.commands._ServoBackward;
import org.usfirst.frc1982.Robot2017.commands._ServoForward;
import org.usfirst.frc1982.Robot2017.commands._Shoot;
import org.usfirst.frc1982.Robot2017.commands._UnlockArm;
import org.usfirst.frc1982.Robot2017.commands._WinchManual;

import edu.wpi.first.wpilibj.Joystick;
import edu.wpi.first.wpilibj.buttons.JoystickButton;


/**
 * This class is the glue that binds the controls on the physical operator
 * interface to the commands and command groups that allow control of the robot.
 */
public class OI {
    //// CREATING BUTTONS
    // One type of button is a joystick button which is any button on a joystick.
    // You create one by telling it which joystick it's on and which button
    // number it is.
    // Joystick stick = new Joystick(port);
    // Button button = new JoystickButton(stick, buttonNumber);

    // There are a few additional built in buttons you can use. Additionally,
    // by subclassing Button you can create custom triggers and bind those to
    // commands the same as any other Button.

    //// TRIGGERING COMMANDS WITH BUTTONS
    // Once you have a button, it's trivial to bind it to a button in one of
    // three ways:

    // Start the command when the button is pressed and let it run the command
    // until it is finished as determined by it's isFinished method.
    // button.whenPressed(new ExampleCommand());

    // Run the command while the button is being held down and interrupt it once
    // the button is released.
    // button.whileHeld(new ExampleCommand());

    // Start the command when the button is released  and let it run the command
    // until it is finished as determined by it's isFinished method.
    // button.whenReleased(new ExampleCommand());


    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    public JoystickButton servoForward;
    public JoystickButton servoBackward;
    public JoystickButton automateServo;
    public JoystickButton shoot;
    public JoystickButton intakeButton;
    public JoystickButton unlockArm;
    public JoystickButton winchManual;
    public JoystickButton agitateServoBackward;
    public JoystickButton agitateServoForward;
    public Joystick driverJoystick;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    
    public OI() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS

        driverJoystick = new Joystick(0);
        
        agitateServoForward = new JoystickButton(driverJoystick, 6);
        agitateServoForward.whenPressed(new _AgitateServoForward());
        agitateServoBackward = new JoystickButton(driverJoystick, 5);
        agitateServoBackward.whenPressed(new _AgitateServoBackward());
        winchManual = new JoystickButton(driverJoystick, 11);
        winchManual.whenPressed(new _WinchManual());
        unlockArm = new JoystickButton(driverJoystick, 11);
        unlockArm.whenPressed(new _UnlockArm());
        intakeButton = new JoystickButton(driverJoystick, 10);
        intakeButton.whileHeld(new _Intake());
        shoot = new JoystickButton(driverJoystick, 1);
        shoot.whenPressed(new _Shoot());
        automateServo = new JoystickButton(driverJoystick, 2);
        automateServo.whileHeld(new _AutomateServo());
        servoBackward = new JoystickButton(driverJoystick, 10);
        servoBackward.whileHeld(new _ServoBackward());
        servoForward = new JoystickButton(driverJoystick, 9);
        servoForward.whileHeld(new _ServoForward());


        // SmartDashboard Buttons

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS

    
    }

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=FUNCTIONS
    public Joystick getDriverJoystick() {
        return driverJoystick;
    }


    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=FUNCTIONS
}

