// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc1982.Robot2017.subsystems;

import org.usfirst.frc1982.Robot2017.RobotMap;
import org.usfirst.frc1982.Robot2017.commands._DriveEnable;
import org.usfirst.frc1982.Robot2017.commands._DriveEnableRaw;

import edu.wpi.first.wpilibj.Encoder;
import edu.wpi.first.wpilibj.RobotDrive;
import edu.wpi.first.wpilibj.SpeedController;
import edu.wpi.first.wpilibj.command.Subsystem;


/**
 *
 */
public class Drive extends Subsystem {

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    private final SpeedController frontLeft = RobotMap.driveFrontLeft;
    private final SpeedController frontRight = RobotMap.driveFrontRight;
    private final SpeedController backLeft = RobotMap.driveBackLeft;
    private final SpeedController backRight = RobotMap.driveBackRight;
//    private final RobotDrive driveTrain = RobotMap.driveDriveTrain;
    private final Encoder encoderFrontLeft = RobotMap.driveEncoderFrontLeft;
    private final Encoder encoderFrontRight = RobotMap.driveEncoderFrontRight;
    private final Encoder encoderBackLeft = RobotMap.driveEncoderBackLeft;
    private final Encoder encoderBackRight = RobotMap.driveEncoderBackRight;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS


    // Put methods for controlling this subsystem
    // here. Call these from Commands.

    public void initDefaultCommand() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND

        setDefaultCommand(new _DriveEnableRaw());

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND
        encoderFrontRight.setDistancePerPulse( 27.0 / 360.0 ); //getDistance() now returns inches traveled
        encoderFrontLeft.setDistancePerPulse( 27.0 / 360.0 );
        encoderBackRight.setDistancePerPulse( 27.0 / (-250.0) );
        encoderBackLeft.setDistancePerPulse( 27.0 / (-120.0) );
        // Set the default command for a subsystem here.
        // setDefaultCommand(new MySpecialCommand());
        
        
    }
}

